#!/usr/bin/env python3
"""
harvest_comments.py - Harvest COMMENTS from the canonical on-topic threads (the
ones literally about how to tell code was written by AI / dead giveaways / signs
ChatGPT wrote it). Comments are where people ENUMERATE the specific code tells,
so this gives the cleanest 100%-on-topic signal plus quotable lines.

Selects thread ids from corpus.jsonl by a STRICT on-topic title pattern that
must also carry a CODE context word (so we don't pull in AI-writing-style or
AI-art threads), then fetches each thread's comments via
/api/comments/search?link_id=<id>. Sequential, resumable (checkpoint by link_id),
reuses the robust get() from collect.

Run:  python3 harvest_comments.py [max_seconds]   (default 600)
Exit: 0 = all selected threads done, 2 = more remain (re-run to resume)
"""
import json, os, time, sys
from collect import get  # robust backoff GET

HERE = os.path.dirname(os.path.abspath(__file__))
CORPUS = os.path.join(HERE, "corpus.jsonl")
COMMENTS = os.path.join(HERE, "comments.jsonl")
CKPT = os.path.join(HERE, "comments_done.txt")

import re
# Title must say someone is identifying/critiquing AI-authored code...
CORE = re.compile(r"(dead\s*giveaway|giveaways?\b|how (can|do) (you|i) tell|how to tell|"
                  r"spot(ting)?\s+ai|tell(s)?\s+(that\s+)?(its|it'?s|something|code|this)\s+ai|"
                  r"screams?\s+ai|ai\s*slop|written by (ai|chat\s?gpt|copilot|claude|an ai)|"
                  r"obvious(ly)?\s+ai|looks like (ai|chat\s?gpt)|generated by (ai|chat\s?gpt)|"
                  r"signs?\b|telltale|red flags?|vibe\s*cod|chat\s?gpt (wrote|code))", re.I)
# ...and the thread must be about CODE, not prose / images.
CTX = re.compile(r"(\bcode\b|coding|codebase|\bfunction\b|\bscript\b|\bprogram|developer|"
                 r"programmer|\bcommit|pull request|\bpr\b|\brepo\b|syntax|snippet|"
                 r"refactor|\bclass\b|software engineer|pull[- ]request|merge request)", re.I)
# drop launch/marketing spam threads
PROMO = re.compile(r"(i'?ll (tell|run|get) you|get you (users|customers)|drop your (link|landing)|"
                   r"first 1,?000 (users|customers)|what are you building|roast my)", re.I)

def select_threads():
    chosen = {}
    if not os.path.exists(CORPUS): return []
    for line in open(CORPUS):
        try: d = json.loads(line)
        except Exception: continue
        t = d.get("title") or ""
        if CORE.search(t) and CTX.search(t) and not PROMO.search(t):
            nc = d.get("num_comments") or 0
            if nc >= 3:
                chosen[d["id"]] = (nc, d.get("subreddit"), t[:90])
    return sorted(chosen.items(), key=lambda kv: -kv[1][0])

def fetch_comments(link_id, max_pages=3):
    out, before = [], None
    for _ in range(max_pages):
        p = {"link_id": link_id, "limit": "100", "sort": "desc"}
        if before: p["before"] = str(before)
        data, st = get("/api/comments/search", p, tries=5)
        time.sleep(0.6)
        if st != "ok" or not data:
            break
        out.extend(data)
        if len(data) < 100:
            break
        before = min(int(x["created_utc"]) for x in data) - 1
    return out

def main():
    budget = float(sys.argv[1]) if len(sys.argv) > 1 else 600.0
    t0 = time.time()
    threads = select_threads()
    done = set()
    if os.path.exists(CKPT):
        done = {l.strip() for l in open(CKPT) if l.strip()}
    seen = set()
    if os.path.exists(COMMENTS):
        for l in open(COMMENTS):
            try: seen.add(json.loads(l)["id"])
            except Exception: pass
    todo = [(i, m) for i, m in threads if i not in done]
    print("[start] on-topic code threads=%d done=%d todo=%d comments_seen=%d"
          % (len(threads), len(done), len(todo), len(seen)), flush=True)

    cf = open(COMMENTS, "a"); ck = open(CKPT, "a")
    n_new = processed = 0
    for link_id, (nc, sub, title) in todo:
        if time.time() - t0 > budget:
            print("[pause] budget hit after %d threads" % processed, flush=True); break
        for c in fetch_comments(link_id):
            cid = c.get("id")
            if not cid or cid in seen: continue
            body = (c.get("body") or "")
            if body in ("[deleted]", "[removed]", ""): continue
            seen.add(cid)
            rec = {"id": cid, "link_id": link_id, "thread_title": title,
                   "subreddit": c.get("subreddit", sub), "score": c.get("score"),
                   "created_utc": c.get("created_utc"),
                   "body": body[:2200], "permalink": c.get("permalink")}
            cf.write(json.dumps(rec, ensure_ascii=False) + "\n"); n_new += 1
        cf.flush()
        ck.write(link_id + "\n"); ck.flush()
        processed += 1
        if processed % 15 == 0:
            print("  [%4.0fs] %d/%d threads, comments=%d" % (time.time()-t0, processed, len(todo), len(seen)), flush=True)
    cf.close(); ck.close()
    print("[end] processed=%d new_comments=%d total=%d remaining=%d"
          % (processed, n_new, len(seen), len(todo)-processed), flush=True)
    sys.exit(0 if processed >= len(todo) else 2)

if __name__ == "__main__":
    main()
